name: Publish to PowerShell Gallery

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish module to PowerShell Gallery
        shell: pwsh
        env:
          NUGET_KEY: ${{ secrets.PSGALLERY_KEY }}
        run: |
          Import-Module PowerShellGet -MinimumVersion 2.2.5 -Force
          Write-Host "Publishing VSCode-Updater to PowerShell Gallery..."

          Publish-Module `
            -Path . `
            -NuGetApiKey $env:NUGET_KEY `
            -ErrorAction Stop

          Write-Host "Publish complete."
