name: Pester Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Register PSGallery
        shell: pwsh
        run: |
          Register-PSRepository -Default -ErrorAction SilentlyContinue
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted

      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -Force -Scope CurrentUser

      - name: Run Tests
        shell: pwsh
        run: |
          Import-Module "$env:GITHUB_WORKSPACE/VSCode-Updater.psm1" -Force
          Get-Command Get-SelectedVersionName | Format-List *
          Invoke-Pester -Path Tests -Output Detailed
